// ============================================
// TIPOS GLOBALES DEL JUEGO "ES IMPOSTOR"
// ============================================

export type Locale = 'es' | 'ca';

export type GameMode = 'list' | 'ai' | 'random';

// Iconos disponibles para los jugadores
export const PLAYER_ICONS = [
  '🦊', '🐱', '🐶', '🐼', '🦁', '🐯', '🐻', '🐨',
  '🐸', '🐵', '🦄', '🐲', '👻', '🤖', '👽', '🎃',
  '🦋', '🐢', '🦀', '🐙', '🦈', '🐬', '🦅', '🦉'
] as const;

export const THEME_CONFIG = [
  { id: 'general', icon: '🎯', color: '#6366f1' },
  { id: 'animals', icon: '🐾', color: '#22c55e' },
  { id: 'food', icon: '🍔', color: '#f97316' },
  { id: 'movies', icon: '🎥', color: '#ec4899' },
  { id: 'sports', icon: '🏆', color: '#14b8a6' },
  { id: 'places', icon: '🌍', color: '#0ea5e9' },
  { id: 'professions', icon: '💼', color: '#8b5cf6' },
  { id: 'technology', icon: '📱', color: '#64748b' },
  { id: 'music', icon: '🎵', color: '#f43f5e' },
  { id: 'history', icon: '🏛️', color: '#a78bfa' },
  { id: 'nature', icon: '🌿', color: '#10b981' },
  { id: 'fantasy', icon: '🔮', color: '#c084fc' },
  { id: 'science', icon: '🧪', color: '#38bdf8' },
  { id: 'art', icon: '🎨', color: '#facc15' },
  { id: 'space', icon: '🚀', color: '#1e293b' },
  { id: 'games', icon: '🎮', color: '#8b5cf6' },
  { id: 'vehicles', icon: '🚗', color: '#ef4444' },
  { id: 'clothes', icon: '👕', color: '#6366f1' },
  { id: 'objects', icon: '📦', color: '#f59e0b' },
  { id: 'body', icon: '🦵', color: '#ec4899' },
  { id: 'school', icon: '🎒', color: '#0ea5e9' },
  { id: 'family', icon: '👨‍👩‍👧‍👦', color: '#8b5cf6' },
  { id: 'actions', icon: '🏃', color: '#f59e0b' }
] as const;

export type PlayerIcon = typeof PLAYER_ICONS[number];

export interface Player {
  id: string;
  name: string;
  icon: PlayerIcon;
  role: 'civil' | 'impostor';
  hasSeenRole: boolean;
  hint?: string;
  impostorClue?: string; // Pista recibida por el impostor
  votedFor?: string; // ID del jugador votado
}

export type GamePhase = 'home' | 'setup' | 'setup-players' | 'online-setup' | 'online-lobby' | 'lobby' | 'turn-reveal' | 'discussion' | 'vote' | 'results' | 'online-hints' | 'online-vote' | 'online-results';

export interface GameConfig {
  mode: GameMode;
  topic: string;
  categories: string[];
  numPlayers: number;
  numImpostors: number;
  impostorClueEnabled?: boolean;
  aiType?: 'suggest' | 'custom';
}

export interface GameState {
  phase: GamePhase;
  config: GameConfig;
  players: Player[];
  secretWord: string;
  currentTurnIndex: number;  // Para revelar roles uno a uno
  currentHintIndex: number;  // Para dar pistas uno a uno
  winner: 'civils' | 'impostor' | null;
}

// Palabras secretas por categoría con palabras similares para el impostor
// Formato: { palabra: [palabrasSimilares] }
export const WORD_DATA: Record<string, Record<string, string[]>> = {
  general: {
    'CASA': ['EDIFICIO', 'HOGAR', 'VIVIENDA'],
    'COCHE': ['VEHÍCULO', 'TRANSPORTE', 'MOTOR'],
    'LIBRO': ['LECTURA', 'PÁGINAS', 'TEXTO'],
    'MESA': ['MUEBLE', 'MADERA', 'SUPERFICIE'],
    'SILLA': ['ASIENTO', 'MUEBLE', 'RESPALDO'],
    'RELOJ': ['TIEMPO', 'HORAS', 'MANECILLAS'],
    'VENTANA': ['CRISTAL', 'ABERTURA', 'LUZ'],
    'PUERTA': ['ENTRADA', 'MADERA', 'ACCESO'],
    'LÁMPARA': ['LUZ', 'ILUMINACIÓN', 'BOMBILLA'],
    'ESPEJO': ['REFLEJO', 'CRISTAL', 'IMAGEN'],
    'TELÉFONO': ['LLAMAR', 'MÓVIL', 'PANTALLA'],
    'ORDENADOR': ['TECNOLOGÍA', 'TECLADO', 'PANTALLA'],
    'TELEVISIÓN': ['PANTALLA', 'CANAL', 'MANDO'],
    'CAMA': ['DORMIR', 'COLCHÓN', 'ALMOHADA'],
    'SOFÁ': ['DESCANSAR', 'SALÓN', 'COJINES'],
    'NEVERA': ['FRÍO', 'COCINA', 'COMIDA'],
    'LAVADORA': ['ROPA', 'AGUA', 'CENTRIFUGAR'],
    'HORNO': ['CALOR', 'COCINAR', 'COMIDA'],
    'DUCHA': ['AGUA', 'BAÑO', 'LIMPIEZA'],
    'ESCALERA': ['SUBIR', 'PELDAÑOS', 'ALTURA'],
    'JARDÍN': ['PLANTAS', 'FLORES', 'VERDE'],
    'PISCINA': ['AGUA', 'NADAR', 'VERANO'],
    'GARAJE': ['COCHE', 'APARCAR', 'PUERTA'],
    'PARAGUAS': ['LLUVIA', 'PROTEGER', 'AGUA'],
    'MALETA': ['VIAJE', 'ROPA', 'EQUIPAJE'],
    'LLAVE': ['PUERTA', 'ABRIR', 'METAL'],
    'MONEDA': ['DINERO', 'METAL', 'VALOR'],
    'TIJERAS': ['CORTAR', 'PAPEL', 'FILO'],
    'BOLÍGRAFO': ['ESCRIBIR', 'TINTA', 'PAPEL'],
    'GAFAS': ['VER', 'CRISTAL', 'OJOS']
  },
  animals: {
    'GATO': ['FELINO', 'MASCOTA', 'MAULLIDO'],
    'PERRO': ['CANINO', 'MASCOTA', 'LADRIDO'],
    'ELEFANTE': ['TROMPA', 'GRANDE', 'SAFARI'],
    'JIRAFA': ['CUELLO', 'MANCHAS', 'ALTO'],
    'LEÓN': ['FELINO', 'MELENA', 'SELVA'],
    'TIGRE': ['RAYAS', 'FELINO', 'NARANJA'],
    'OSO': ['PELUDO', 'GARRAS', 'HIBERNAR'],
    'DELFÍN': ['MARINO', 'ALETA', 'INTELIGENTE'],
    'ÁGUILA': ['AVE', 'VUELO', 'PICO'],
    'SERPIENTE': ['REPTIL', 'ESCAMAS', 'VENENO'],
    'CABALLO': ['EQUINO', 'MONTAR', 'GALOPE'],
    'CONEJO': ['OREJAS', 'SALTAR', 'ZANAHORIA'],
    'RATÓN': ['PEQUEÑO', 'ROEDOR', 'QUESO'],
    'CERDO': ['GRANJA', 'ROSA', 'OINK'],
    'VACA': ['LECHE', 'GRANJA', 'MUGIR'],
    'GALLINA': ['HUEVOS', 'PLUMAS', 'CACAREAR'],
    'PATO': ['AGUA', 'PICO', 'CUAC'],
    'MONO': ['PLÁTANO', 'TREPAR', 'SELVA'],
    'BALLENA': ['OCÉANO', 'GRANDE', 'CHORRO'],
    'TIBURÓN': ['MAR', 'DIENTES', 'ALETA'],
    'PULPO': ['TENTÁCULOS', 'MAR', 'TINTA'],
    'CANGREJO': ['PINZAS', 'PLAYA', 'ROJO'],
    'TORTUGA': ['CAPARAZÓN', 'LENTA', 'REPTIL'],
    'COCODRILO': ['MANDÍBULA', 'PANTANO', 'REPTIL'],
    'PINGÜINO': ['HIELO', 'ANTÁRTIDA', 'BLANCO Y NEGRO'],
    'LORO': ['HABLAR', 'COLORES', 'PLUMAS'],
    'BÚHO': ['NOCHE', 'OJOS', 'SABIO'],
    'MURCIÉLAGO': ['NOCHE', 'CUEVA', 'VOLAR'],
    'ARAÑA': ['TELARAÑA', 'PATAS', 'INSECTO'],
    'MARIPOSA': ['ALAS', 'COLORES', 'FLOR']
  },
  food: {
    'PIZZA': ['ITALIANO', 'HORNO', 'QUESO'],
    'PASTA': ['ITALIANO', 'FIDEOS', 'SALSA'],
    'SUSHI': ['JAPONÉS', 'ARROZ', 'PESCADO'],
    'TACOS': ['MEXICANO', 'TORTILLA', 'PICANTE'],
    'PAELLA': ['ESPAÑOL', 'ARROZ', 'MARISCOS'],
    'HAMBURGUESA': ['AMERICANO', 'CARNE', 'PAN'],
    'ENSALADA': ['VERDURAS', 'FRESCO', 'SANO'],
    'HELADO': ['FRÍO', 'DULCE', 'POSTRE'],
    'CHOCOLATE': ['DULCE', 'CACAO', 'POSTRE'],
    'FRUTA': ['NATURAL', 'DULCE', 'VITAMINAS'],
    'PAN': ['HORNO', 'TRIGO', 'DESAYUNO'],
    'ARROZ': ['GRANO', 'ASIÁTICO', 'BLANCO'],
    'POLLO': ['CARNE', 'AVE', 'ASADO'],
    'PESCADO': ['MAR', 'OMEGA', 'FRESCO'],
    'HUEVO': ['GALLINA', 'PROTEÍNA', 'FRITO'],
    'QUESO': ['LÁCTEO', 'AMARILLO', 'DERRETIR'],
    'LECHE': ['VACA', 'BLANCO', 'CALCIO'],
    'CAFÉ': ['CAFEÍNA', 'NEGRO', 'MAÑANA'],
    'TÉ': ['INFUSIÓN', 'CALIENTE', 'TAZA'],
    'CERVEZA': ['ALCOHOL', 'ESPUMA', 'BAR'],
    'VINO': ['UVA', 'COPA', 'TINTO'],
    'TORTILLA': ['HUEVO', 'ESPAÑOL', 'PATATA'],
    'BOCADILLO': ['PAN', 'JAMÓN', 'RÁPIDO'],
    'CROQUETA': ['FRITO', 'BECHAMEL', 'JAMÓN'],
    'GAZPACHO': ['FRÍO', 'TOMATE', 'VERANO'],
    'CHURROS': ['CHOCOLATE', 'DULCE', 'DESAYUNO'],
    'TARTA': ['CUMPLEAÑOS', 'DULCE', 'VELAS'],
    'GALLETA': ['DULCE', 'CRUJIENTE', 'TÉ'],
    'CARAMELO': ['DULCE', 'AZÚCAR', 'NIÑOS'],
    'PATATAS FRITAS': ['CRUJIENTE', 'SAL', 'SNACK']
  },
  movies: {
    'TITANIC': ['BARCO', 'NAUFRAGIO', 'ROMANCE'],
    'AVATAR': ['AZUL', 'ALIENS', 'SELVA'],
    'MATRIX': ['VIRTUAL', 'HACKER', 'NEGRO'],
    'GLADIATOR': ['ROMA', 'ARENA', 'ESPADA'],
    'INCEPTION': ['SUEÑOS', 'MENTE', 'CAPAS'],
    'JOKER': ['PAYASO', 'VILLANO', 'RISA'],
    'FROZEN': ['HIELO', 'PRINCESA', 'CANCIÓN'],
    'COCO': ['MÚSICA', 'MUERTOS', 'FAMILIA'],
    'UP': ['GLOBOS', 'AVENTURA', 'ABUELO'],
    'SHREK': ['OGRO', 'VERDE', 'PANTANO'],
    'SPIDER-MAN': ['ARAÑA', 'HÉROE', 'TELARAÑA'],
    'BATMAN': ['MURCIÉLAGO', 'GOTHAM', 'OSCURO'],
    'IRON MAN': ['ROBOT', 'STARK', 'ARMADURA'],
    'TOY STORY': ['JUGUETES', 'WOODY', 'PIXAR'],
    'FINDING NEMO': ['PEZ', 'OCÉANO', 'PADRE'],
    'EL REY LEÓN': ['SIMBA', 'SABANA', 'MUFASA'],
    'HARRY POTTER': ['MAGIA', 'VARITA', 'HOGWARTS'],
    'STAR WARS': ['ESPACIO', 'LÁSER', 'FUERZA'],
    'JURASSIC PARK': ['DINOSAURIOS', 'PARQUE', 'FÓSILES'],
    'PIRATES OF THE CARIBBEAN': ['BARCO', 'JACK SPARROW', 'TESORO'],
    'LORD OF THE RINGS': ['ANILLO', 'FRODO', 'MORDOR'],
    'AVENGERS': ['HÉROES', 'THANOS', 'MARVEL'],
    'MINIONS': ['AMARILLO', 'BANANA', 'PEQUEÑOS'],
    'MOANA': ['MAR', 'ISLA', 'MAUI'],
    'ENCANTO': ['COLOMBIA', 'MAGIA', 'FAMILIA'],
    'SOUL': ['JAZZ', 'ALMA', 'PIXAR'],
    'RATATOUILLE': ['RATA', 'COCINA', 'PARÍS'],
    'WALL-E': ['ROBOT', 'BASURA', 'ESPACIO'],
    'INSIDE OUT': ['EMOCIONES', 'ALEGRÍA', 'MENTE'],
    'THE GODFATHER': ['MAFIA', 'ITALIA', 'FAMILIA']
  },
  sports: {
    'FÚTBOL': ['BALÓN', 'GOL', 'PORTERÍA'],
    'BALONCESTO': ['CANASTA', 'NBA', 'DRIBLING'],
    'TENIS': ['RAQUETA', 'RED', 'PELOTA'],
    'NATACIÓN': ['AGUA', 'PISCINA', 'BRAZADAS'],
    'CICLISMO': ['BICICLETA', 'PEDALES', 'RUEDAS'],
    'BOXEO': ['GUANTES', 'RING', 'GOLPE'],
    'GOLF': ['PALO', 'HOYO', 'CÉSPED'],
    'ESQUÍ': ['NIEVE', 'MONTAÑA', 'BASTONES'],
    'SURF': ['OLA', 'TABLA', 'PLAYA'],
    'PATINAJE': ['HIELO', 'PATINES', 'PIRUETA'],
    'ATLETISMO': ['CORRER', 'PISTA', 'MEDALLA'],
    'VOLEIBOL': ['RED', 'REMATE', 'PLAYA'],
    'BÉISBOL': ['BATE', 'GUANTE', 'PELOTA'],
    'RUGBY': ['OVAL', 'PLACAJE', 'ENSAYO'],
    'HOCKEY': ['PUCK', 'STICK', 'HIELO'],
    'GIMNASIA': ['ACROBACIA', 'EQUILIBRIO', 'APARATOS'],
    'ESCALADA': ['ROCA', 'CUERDA', 'ALTURA'],
    'KARATE': ['ARTES MARCIALES', 'CINTURÓN', 'KATA'],
    'JUDO': ['TATAMI', 'LLAVE', 'JAPÓN'],
    'ESGRIMA': ['ESPADA', 'MÁSCARA', 'TOQUE'],
    'BÁDMINTON': ['PLUMA', 'RAQUETA', 'RED'],
    'PING PONG': ['MESA', 'PALETA', 'PELOTA'],
    'POLO': ['CABALLO', 'MAZO', 'PELOTA'],
    'WATERPOLO': ['AGUA', 'PORTERÍA', 'GORRO'],
    'TRIATLÓN': ['NADAR', 'CORRER', 'BICI'],
    'MARATÓN': ['42KM', 'CORRER', 'RESISTENCIA'],
    'SNOWBOARD': ['NIEVE', 'TABLA', 'MONTAÑA'],
    'SKATE': ['TABLA', 'RUEDAS', 'TRUCOS'],
    'BMX': ['BICI', 'TRUCOS', 'RAMPA'],
    'PARKOUR': ['SALTAR', 'OBSTÁCULOS', 'URBANO']
  },
  places: {
    'PLAYA': ['ARENA', 'MAR', 'SOL'],
    'MONTAÑA': ['ALTURA', 'NIEVE', 'ESCALAR'],
    'BOSQUE': ['ÁRBOLES', 'VERDE', 'ANIMALES'],
    'DESIERTO': ['ARENA', 'CALOR', 'OASIS'],
    'SELVA': ['TROPICAL', 'ANIMALES', 'LLUVIA'],
    'ISLA': ['MAR', 'PALMERA', 'VACACIONES'],
    'VOLCÁN': ['LAVA', 'ERUPCIÓN', 'CRÁTER'],
    'CUEVA': ['OSCURO', 'ESTALACTITAS', 'MURCIÉLAGOS'],
    'CASCADA': ['AGUA', 'CAER', 'RÍO'],
    'LAGO': ['AGUA DULCE', 'PESCA', 'BOTE'],
    'RÍO': ['AGUA', 'CORRIENTE', 'PUENTE'],
    'OCÉANO': ['PROFUNDO', 'SALADO', 'OLAS'],
    'GLACIAR': ['HIELO', 'FRÍO', 'ÁRTICO'],
    'CAMPO': ['VERDE', 'CULTIVO', 'RURAL'],
    'CIUDAD': ['EDIFICIOS', 'TRÁFICO', 'URBANO'],
    'PUEBLO': ['PEQUEÑO', 'TRANQUILO', 'RURAL'],
    'CASTILLO': ['MEDIEVAL', 'TORRE', 'REY'],
    'MUSEO': ['ARTE', 'HISTORIA', 'CUADROS'],
    'PARQUE': ['VERDE', 'JUEGOS', 'PASEO'],
    'ZOO': ['ANIMALES', 'JAULAS', 'VISITA'],
    'HOSPITAL': ['MÉDICO', 'ENFERMO', 'CURA'],
    'ESCUELA': ['ESTUDIAR', 'PROFESOR', 'ALUMNOS'],
    'BIBLIOTECA': ['LIBROS', 'SILENCIO', 'LEER'],
    'AEROPUERTO': ['AVIÓN', 'VIAJAR', 'MALETA'],
    'ESTACIÓN': ['TREN', 'ANDÉN', 'VIAJE'],
    'SUPERMERCADO': ['COMPRAR', 'CARRITO', 'COMIDA'],
    'RESTAURANTE': ['COMER', 'MENÚ', 'CAMARERO'],
    'CINE': ['PELÍCULA', 'PALOMITAS', 'PANTALLA'],
    'TEATRO': ['OBRA', 'ESCENARIO', 'ACTORES'],
    'ESTADIO': ['DEPORTE', 'AFICIONADOS', 'PARTIDO']
  },
  professions: {
    'MÉDICO': ['HOSPITAL', 'CURAR', 'BATA'],
    'PROFESOR': ['ESCUELA', 'ENSEÑAR', 'PIZARRA'],
    'POLICÍA': ['SEGURIDAD', 'UNIFORME', 'LEY'],
    'BOMBERO': ['FUEGO', 'MANGUERA', 'RESCATE'],
    'CHEF': ['COCINA', 'COMIDA', 'GORRO'],
    'PILOTO': ['AVIÓN', 'VOLAR', 'CABINA'],
    'ASTRONAUTA': ['ESPACIO', 'COHETE', 'LUNA'],
    'ABOGADO': ['JUSTICIA', 'TRIBUNAL', 'LEYES'],
    'ARQUITECTO': ['EDIFICIOS', 'PLANOS', 'DISEÑO'],
    'INGENIERO': ['MÁQUINAS', 'CONSTRUIR', 'TÉCNICO'],
    'CIENTÍFICO': ['LABORATORIO', 'EXPERIMENTO', 'DESCUBRIR'],
    'VETERINARIO': ['ANIMALES', 'CURAR', 'CLÍNICA'],
    'DENTISTA': ['DIENTES', 'MUELAS', 'DOLOR'],
    'ENFERMERO': ['HOSPITAL', 'CUIDAR', 'JERINGA'],
    'PERIODISTA': ['NOTICIAS', 'ENTREVISTA', 'ESCRIBIR'],
    'FOTÓGRAFO': ['CÁMARA', 'FOTO', 'IMAGEN'],
    'PINTOR': ['CUADRO', 'PINCEL', 'COLORES'],
    'MÚSICO': ['INSTRUMENTO', 'CANCIÓN', 'CONCIERTO'],
    'ACTOR': ['TEATRO', 'PELÍCULA', 'PAPEL'],
    'CANTANTE': ['VOZ', 'MICRÓFONO', 'ESCENARIO'],
    'FUTBOLISTA': ['BALÓN', 'GOL', 'ESTADIO'],
    'CARPINTERO': ['MADERA', 'HERRAMIENTAS', 'MUEBLE'],
    'ELECTRICISTA': ['CABLES', 'ENCHUFE', 'LUZ'],
    'FONTANERO': ['TUBERÍAS', 'AGUA', 'GRIFO'],
    'MECÁNICO': ['COCHE', 'MOTOR', 'TALLER'],
    'PELUQUERO': ['PELO', 'TIJERAS', 'CORTE'],
    'PANADERO': ['PAN', 'HORNO', 'MASA'],
    'AGRICULTOR': ['CAMPO', 'CULTIVAR', 'COSECHA'],
    'PESCADOR': ['MAR', 'RED', 'PECES'],
    'CARTERO': ['CARTAS', 'BUZÓN', 'ENTREGAR']
  },
  technology: {
    'SMARTPHONE': ['MÓVIL', 'APP', 'PANTALLA TÁCTIL'],
    'TABLET': ['PANTALLA', 'PORTÁTIL', 'APPLE'],
    'LAPTOP': ['ORDENADOR', 'PORTÁTIL', 'TECLADO'],
    'SMARTWATCH': ['RELOJ', 'NOTIFICACIONES', 'MUÑECA'],
    'AURICULARES': ['MÚSICA', 'OREJAS', 'BLUETOOTH'],
    'CÁMARA': ['FOTO', 'VÍDEO', 'LENTE'],
    'DRON': ['VOLAR', 'CONTROL REMOTO', 'CÁMARA'],
    'ROBOT': ['AUTOMÁTICO', 'MÁQUINA', 'IA'],
    'CONSOLA': ['VIDEOJUEGOS', 'MANDO', 'PLAY'],
    'WIFI': ['INTERNET', 'CONEXIÓN', 'ROUTER'],
    'BLUETOOTH': ['INALÁMBRICO', 'CONEXIÓN', 'AURICULARES'],
    'GPS': ['NAVEGACIÓN', 'MAPA', 'UBICACIÓN'],
    'USB': ['PENDRIVE', 'CONEXIÓN', 'DATOS'],
    'IMPRESORA': ['PAPEL', 'TINTA', 'DOCUMENTO'],
    'PROYECTOR': ['IMAGEN', 'PANTALLA', 'PRESENTACIÓN'],
    'MICRÓFONO': ['VOZ', 'SONIDO', 'GRABAR'],
    'ALTAVOZ': ['SONIDO', 'MÚSICA', 'VOLUMEN'],
    'TELEVISOR': ['PANTALLA', 'CANALES', 'SMART'],
    'BATERÍA': ['CARGA', 'ENERGÍA', 'RECARGABLE'],
    'CHIP': ['PROCESADOR', 'ELECTRÓNICO', 'PEQUEÑO'],
    'SERVIDOR': ['DATOS', 'CLOUD', 'HOSTING'],
    'APP': ['APLICACIÓN', 'MÓVIL', 'DESCARGAR'],
    'VIDEOJUEGO': ['PLAY', 'MANDO', 'PANTALLA'],
    'REALIDAD VIRTUAL': ['GAFAS', 'VR', '3D'],
    'INTELIGENCIA ARTIFICIAL': ['ROBOT', 'MÁQUINA', 'APRENDER'],
    'STREAMING': ['VÍDEO', 'DIRECTO', 'INTERNET'],
    'PODCAST': ['AUDIO', 'EPISODIO', 'ESCUCHAR'],
    'CRIPTOMONEDA': ['BITCOIN', 'DIGITAL', 'BLOCKCHAIN'],
    'REDES SOCIALES': ['INSTAGRAM', 'LIKES', 'SEGUIDORES'],
    'EMAIL': ['CORREO', 'MENSAJE', 'ENVIAR']
  },
  music: {
    'GUITARRA': ['CUERDAS', 'RASGUEAR', 'ACÚSTICA'],
    'PIANO': ['TECLAS', 'CLÁSICO', 'MELODÍA'],
    'BATERÍA': ['BAQUETAS', 'RITMO', 'PERCUSIÓN'],
    'VIOLÍN': ['ARCO', 'CUERDAS', 'ORQUESTA'],
    'FLAUTA': ['VIENTO', 'SOPLAR', 'MADERA'],
    'TROMPETA': ['METAL', 'JAZZ', 'SOPLAR'],
    'SAXOFÓN': ['JAZZ', 'METAL', 'VIENTO'],
    'ARPA': ['CUERDAS', 'ÁNGEL', 'GRANDE'],
    'ACORDEÓN': ['FUELLE', 'BOTONES', 'FOLK'],
    'UKELELE': ['HAWAIANO', 'PEQUEÑO', 'CUERDAS'],
    'BAJO': ['GRAVES', 'CUERDAS', 'BANDA'],
    'CANTANTE': ['VOZ', 'ESCENARIO', 'MICRÓFONO'],
    'CONCIERTO': ['DIRECTO', 'MÚSICA', 'PÚBLICO'],
    'DISCO': ['VINILO', 'ÁLBUM', 'MÚSICA'],
    'CANCIÓN': ['LETRA', 'MELODÍA', 'RITMO'],
    'ROCK': ['ELÉCTRICO', 'GUITARRA', 'FUERTE'],
    'POP': ['POPULAR', 'PEGADIZO', 'RADIO'],
    'JAZZ': ['IMPROVISACIÓN', 'SAXO', 'CLUB'],
    'REGGAETON': ['LATINO', 'RITMO', 'URBANO'],
    'FLAMENCO': ['ESPAÑOL', 'GUITARRA', 'BAILE'],
    'ÓPERA': ['SOPRANO', 'TEATRO', 'CLÁSICO'],
    'RAP': ['RIMA', 'FLOW', 'URBANO'],
    'ORQUESTA': ['DIRECTOR', 'INSTRUMENTOS', 'SINFONÍA'],
    'DJ': ['MEZCLA', 'DISCOTECA', 'VINILO'],
    'KARAOKE': ['CANTAR', 'PANTALLA', 'LETRA'],
    'HIMNO': ['PAÍS', 'OFICIAL', 'SOLEMNE'],
    'VILLANCICO': ['NAVIDAD', 'CANTAR', 'TRADICIONAL'],
    'BANDA SONORA': ['PELÍCULA', 'MÚSICA', 'CINE'],
    'SPOTIFY': ['STREAMING', 'PLAYLIST', 'MÚSICA'],
    'MICRÓFONO': ['CANTAR', 'VOZ', 'GRABAR'],
    'AMPLIFICADOR': ['SONIDO', 'VOLUMEN', 'GUITARRA'],
    'ESTUDIO': ['GRABAR', 'MÚSICA', 'MEZCLA'],
    'PARTITURA': ['NOTAS', 'PAPEL', 'LEER'],
    'CORO': ['VOCES', 'CANTAR', 'GRUPO'],
    'TAMBOR': ['PERCUSIÓN', 'GOLPEAR', 'RITMO'],
    'MARACAS': ['AGITAR', 'RITMO', 'LATINO'],
    'PANDERETA': ['PERCUSIÓN', 'METAL', 'AGITAR'],
    'ARMÓNICA': ['BOCA', 'BLUES', 'PEQUEÑO'],
    'SINTETIZADOR': ['ELECTRÓNICO', 'TECLAS', 'SONIDO'],
    'CASTAÑUELAS': ['FLAMENCO', 'DEDOS', 'RITMO'],
    'XILÓFONO': ['LÁMINAS', 'MAZAS', 'INFANTIL'],
    'GAITA': ['ESCOCIA', 'SOPLAR', 'FUELLE'],
    'BANJO': ['COUNTRY', 'CUERDAS', 'AMERICANO'],
    'MANDOLINA': ['CUERDAS', 'ITALIANO', 'PEQUEÑO'],
    'CONTRABAJO': ['GRANDE', 'CUERDAS', 'GRAVES'],
    'CLARINETE': ['VIENTO', 'MADERA', 'NEGRO'],
    'OBOE': ['VIENTO', 'ORQUESTA', 'MADERA'],
    'TUBA': ['GRANDE', 'METAL', 'GRAVES'],
    'TRIÁNGULO': ['METAL', 'GOLPEAR', 'SIMPLE']
  },
  history: {
    'PIRÁMIDE': ['EGIPTO', 'FARAÓN', 'ANTIGUO'],
    'GLADIADOR': ['ROMA', 'ARENA', 'LUCHA'],
    'FARAÓN': ['EGIPTO', 'REY', 'MOMIA'],
    'VIKINGO': ['NORTE', 'BARCO', 'GUERRERO'],
    'SAMURÁI': ['JAPÓN', 'ESPADA', 'HONOR'],
    'CABALLERO': ['MEDIEVAL', 'ARMADURA', 'CABALLO'],
    'DINOSAURIO': ['PREHISTORIA', 'FÓSIL', 'EXTINTO'],
    'MOMIA': ['EGIPTO', 'VENDAS', 'TUMBA'],
    'COLÓN': ['AMÉRICA', 'DESCUBRIR', 'BARCO'],
    'CLEOPATRA': ['EGIPTO', 'REINA', 'BELLEZA'],
    'NAPOLEÓN': ['FRANCIA', 'EMPERADOR', 'GUERRA'],
    'JULIO CÉSAR': ['ROMA', 'EMPERADOR', 'TRAICIÓN'],
    'ALEJANDRO MAGNO': ['GRECIA', 'CONQUISTADOR', 'IMPERIO'],
    'ESPARTACO': ['GLADIADOR', 'REBELIÓN', 'ESCLAVO'],
    'LEONARDO DA VINCI': ['RENACIMIENTO', 'INVENTOR', 'ARTE'],
    'MIGUEL ÁNGEL': ['ESCULTOR', 'RENACIMIENTO', 'CAPILLA'],
    'GALILEO': ['TELESCOPIO', 'CIENCIA', 'PLANETA'],
    'EINSTEIN': ['GENIO', 'RELATIVIDAD', 'FÍSICA'],
    'EDISON': ['BOMBILLA', 'INVENTOR', 'ELECTRICIDAD'],
    'REVOLUCIÓN': ['CAMBIO', 'PUEBLO', 'LUCHA'],
    'GUERRA MUNDIAL': ['CONFLICTO', 'PAÍSES', 'SOLDADOS'],
    'IMPERIO ROMANO': ['CÉSAR', 'COLISEO', 'LEGIONES'],
    'EDAD MEDIA': ['CASTILLOS', 'FEUDAL', 'CABALLEROS'],
    'RENACIMIENTO': ['ARTE', 'CULTURA', 'ITALIA'],
    'INDEPENDENCIA': ['LIBERTAD', 'PAÍS', 'LUCHA'],
    'CONQUISTA': ['TERRITORIO', 'GUERRA', 'DOMINAR'],
    'ESCLAVITUD': ['INJUSTICIA', 'CADENAS', 'LIBERTAD'],
    'MURALLA CHINA': ['CHINA', 'DEFENSA', 'GRANDE'],
    'COLISEO': ['ROMA', 'GLADIADORES', 'ARENA'],
    'STONEHENGE': ['PIEDRAS', 'MISTERIO', 'ANTIGUO'],
    'MACHU PICCHU': ['INCA', 'PERÚ', 'MONTAÑA'],
    'TITANIC': ['BARCO', 'HUNDIRSE', 'ICEBERG'],
    'BERLÍN': ['MURO', 'ALEMANIA', 'DIVIDIDO'],
    'HIROSHIMA': ['BOMBA', 'JAPÓN', 'GUERRA'],
    'APOLO 11': ['LUNA', 'NASA', 'ASTRONAUTA'],
    'FÓSIL': ['PREHISTORIA', 'HUESOS', 'ANTIGUO'],
    'PERGAMINO': ['ANTIGUO', 'ESCRIBIR', 'PAPEL'],
    'ARMADURA': ['METAL', 'CABALLERO', 'PROTECCIÓN'],
    'CATAPULTA': ['GUERRA', 'LANZAR', 'MEDIEVAL'],
    'CARROZA': ['CABALLOS', 'RUEDAS', 'TRANSPORTE'],
    'ESPADA': ['METAL', 'LUCHA', 'FILO'],
    'ESCUDO': ['DEFENSA', 'METAL', 'PROTEGER'],
    'CORONA': ['REY', 'ORO', 'JOYA'],
    'TRONO': ['REY', 'ASIENTO', 'PODER'],
    'CASTILLO': ['MEDIEVAL', 'PIEDRA', 'TORRE'],
    'TORRE': ['ALTA', 'PIEDRA', 'VIGILAR'],
    'FOSO': ['AGUA', 'CASTILLO', 'DEFENSA'],
    'PUENTE LEVADIZO': ['CASTILLO', 'ENTRADA', 'CADENAS'],
    'JEROGLÍFICO': ['EGIPTO', 'SÍMBOLO', 'ESCRIBIR']
  },
  nature: {
    'ÁRBOL': ['HOJAS', 'TRONCO', 'RAÍCES'],
    'FLOR': ['PÉTALOS', 'AROMA', 'COLORES'],
    'MONTAÑA': ['ALTURA', 'ROCA', 'NIEVE'],
    'RÍO': ['AGUA', 'CORRIENTE', 'PECES'],
    'OCÉANO': ['SALADO', 'OLAS', 'PROFUNDO'],
    'BOSQUE': ['ÁRBOLES', 'VERDE', 'ANIMALES'],
    'DESIERTO': ['ARENA', 'CALOR', 'SECO'],
    'SELVA': ['TROPICAL', 'HÚMEDO', 'ANIMALES'],
    'VOLCÁN': ['LAVA', 'FUEGO', 'ERUPCIÓN'],
    'TERREMOTO': ['TEMBLAR', 'TIERRA', 'DESTRUCCIÓN'],
    'TORNADO': ['VIENTO', 'GIRAR', 'DESTRUCCIÓN'],
    'HURACÁN': ['VIENTO', 'LLUVIA', 'TROPICAL'],
    'TSUNAMI': ['OLA', 'GIGANTE', 'MAR'],
    'AURORA BOREAL': ['LUCES', 'NORTE', 'CIELO'],
    'ARCOÍRIS': ['COLORES', 'LLUVIA', 'SOL'],
    'RAYO': ['ELECTRICIDAD', 'TORMENTA', 'LUZ'],
    'TRUENO': ['SONIDO', 'TORMENTA', 'RAYO'],
    'NIEVE': ['FRÍO', 'BLANCO', 'INVIERNO'],
    'LLUVIA': ['AGUA', 'GOTAS', 'NUBES'],
    'SOL': ['CALOR', 'LUZ', 'ESTRELLA'],
    'LUNA': ['NOCHE', 'SATÉLITE', 'FASES'],
    'ESTRELLA': ['BRILLA', 'NOCHE', 'CIELO'],
    'COMETA': ['COLA', 'ESPACIO', 'HIELO'],
    'ECLIPSE': ['SOL', 'LUNA', 'OSCURIDAD'],
    'CUEVA': ['OSCURO', 'ROCA', 'MURCIÉLAGOS'],
    'CASCADA': ['AGUA', 'CAER', 'RUIDO'],
    'GLACIAR': ['HIELO', 'FRÍO', 'GRANDE'],
    'CORAL': ['MAR', 'COLORES', 'PECES'],
    'ISLA': ['MAR', 'TIERRA', 'AISLADO'],
    'PANTANO': ['AGUA', 'BARRO', 'MOSQUITOS'],
    'PRADERA': ['HIERBA', 'VERDE', 'PLANO'],
    'SABANA': ['ÁFRICA', 'LEONES', 'SECO'],
    'TUNDRA': ['FRÍO', 'HIELO', 'NORTE'],
    'JUNGLA': ['TROPICAL', 'VERDE', 'ANIMALES'],
    'OASIS': ['DESIERTO', 'AGUA', 'PALMERAS'],
    'GÉISER': ['AGUA', 'CALIENTE', 'VAPOR'],
    'CRÁTER': ['VOLCÁN', 'HOYO', 'METEORITO'],
    'ACANTILADO': ['ROCA', 'MAR', 'ALTO'],
    'PLAYA': ['ARENA', 'MAR', 'SOL'],
    'COSTA': ['MAR', 'TIERRA', 'ORILLA'],
    'BAHÍA': ['MAR', 'TIERRA', 'PROTEGIDO'],
    'PENÍNSULA': ['TIERRA', 'MAR', 'CASI ISLA'],
    'CABO': ['PUNTA', 'MAR', 'TIERRA'],
    'DELTA': ['RÍO', 'DESEMBOCADURA', 'TRIÁNGULO'],
    'MANANTIAL': ['AGUA', 'BROTAR', 'NATURAL'],
    'GRUTA': ['CUEVA', 'ROCA', 'OSCURO'],
    'ARRECIFE': ['CORAL', 'MAR', 'PECES'],
    'LAGUNA': ['AGUA', 'SALADA', 'PEQUEÑA'],
    'MARISMA': ['AGUA', 'SAL', 'AVES'],
    'CAÑÓN': ['PROFUNDO', 'RÍO', 'ROCA']
  },
  fantasy: {
    'DRAGÓN': ['FUEGO', 'ALAS', 'ESCAMAS'],
    'UNICORNIO': ['CUERNO', 'MÁGICO', 'CABALLO'],
    'HADA': ['ALAS', 'PEQUEÑA', 'VARITA'],
    'MAGO': ['VARITA', 'HECHIZO', 'BARBA'],
    'BRUJA': ['ESCOBA', 'CALDERO', 'HECHIZO'],
    'ELFO': ['OREJAS', 'BOSQUE', 'ARCO'],
    'ENANO': ['PEQUEÑO', 'MINA', 'BARBA'],
    'GIGANTE': ['GRANDE', 'FUERTE', 'ALTO'],
    'TROLL': ['FEO', 'PUENTE', 'GRANDE'],
    'OGRO': ['VERDE', 'GRANDE', 'PANTANO'],
    'SIRENA': ['COLA', 'MAR', 'CANTAR'],
    'CENTAURO': ['CABALLO', 'HUMANO', 'ARCO'],
    'FÉNIX': ['FUEGO', 'RENACER', 'AVE'],
    'GRIFO': ['ÁGUILA', 'LEÓN', 'ALAS'],
    'PEGASO': ['CABALLO', 'ALAS', 'VOLAR'],
    'MEDUSA': ['SERPIENTES', 'PIEDRA', 'MIRADA'],
    'CÍCLOPE': ['OJO', 'GIGANTE', 'UNO'],
    'MINOTAURO': ['TORO', 'LABERINTO', 'HUMANO'],
    'KRAKEN': ['PULPO', 'GIGANTE', 'MAR'],
    'VAMPIRO': ['SANGRE', 'COLMILLOS', 'NOCHE'],
    'HOMBRE LOBO': ['LUNA', 'TRANSFORMACIÓN', 'LOBO'],
    'ZOMBI': ['MUERTO', 'CAMINAR', 'CEREBRO'],
    'FANTASMA': ['TRANSPARENTE', 'MUERTO', 'ASUSTAR'],
    'MOMIA': ['VENDAS', 'EGIPTO', 'MALDICIÓN'],
    'ESQUELETO': ['HUESOS', 'MUERTO', 'CAMINAR'],
    'GÓLEM': ['BARRO', 'ARTIFICIAL', 'GRANDE'],
    'BASILISCO': ['SERPIENTE', 'MIRADA', 'MORTAL'],
    'HIDRA': ['CABEZAS', 'SERPIENTE', 'AGUA'],
    'QUIMERA': ['HÍBRIDO', 'MONSTRUO', 'FUEGO'],
    'CERBERO': ['PERRO', 'TRES CABEZAS', 'INFIERNO'],
    'LEVIATÁN': ['MAR', 'MONSTRUO', 'GIGANTE'],
    'DEMONIO': ['CUERNOS', 'INFIERNO', 'MALVADO'],
    'ÁNGEL': ['ALAS', 'CIELO', 'BONDAD'],
    'GREMLIN': ['PEQUEÑO', 'TRAVIESO', 'MÁQUINAS'],
    'DUENDE': ['PEQUEÑO', 'TRAVIESO', 'ORO'],
    'GNOMO': ['JARDÍN', 'PEQUEÑO', 'BARBA'],
    'NINFA': ['NATURALEZA', 'HERMOSA', 'BOSQUE'],
    'TRITÓN': ['MAR', 'COLA', 'TRIDENTE'],
    'LICÁNTROPO': ['LOBO', 'LUNA', 'TRANSFORMAR'],
    'ESFINGE': ['ENIGMA', 'LEÓN', 'HUMANO'],
    'AVE FÉNIX': ['RENACER', 'FUEGO', 'INMORTAL'],
    'BANSHEE': ['GRITO', 'MUERTE', 'FANTASMA'],
    'YETI': ['NIEVE', 'GRANDE', 'PELUDO'],
    'PIE GRANDE': ['BOSQUE', 'GRANDE', 'MISTERIO'],
    'DJINN': ['LÁMPARA', 'DESEOS', 'ÁRABE'],
    'HIPOGRIFO': ['ÁGUILA', 'CABALLO', 'ALAS'],
    'CANCERBERO': ['PERRO', 'INFIERNO', 'GUARDIA'],
    'POLTERGEIST': ['OBJETOS', 'FANTASMA', 'MOVER'],
    'ARPÍA': ['AVE', 'MUJER', 'GARRAS'],
    'WENDIGO': ['CANÍBAL', 'FRÍO', 'DEMONIO']
  },
  vehicles: {
    'COCHE': ['RUEDAS', 'MOTOR', 'CARRETERA'],
    'MOTO': ['CASCO', 'DOS RUEDAS', 'MANILLAR'],
    'AUTOBÚS': ['PASAJEROS', 'GRANDE', 'PARADA'],
    'TREN': ['VÍAS', 'VAGONES', 'ESTACIÓN'],
    'AVIÓN': ['ALAS', 'VOLAR', 'AEROPUERTO'],
    'BARCO': ['MAR', 'NAVEGAR', 'PUERTO'],
    'BICICLETA': ['PEDALES', 'CADENA', 'MANILLAR'],
    'HELICÓPTERO': ['HÉLICES', 'VOLAR', 'RUIDO'],
    'CAMIÓN': ['CARGA', 'GRANDE', 'CARRETERA'],
    'SUBMARINO': ['BAJO EL AGUA', 'MAR', 'PROFUNDO'],
    'PATINETE': ['RUEDAS', 'EQUILIBRIO', 'MANILLAR'],
    'TAXI': ['PAGAR', 'COCHE', 'TRANSPORTE'],
    'AMBULANCIA': ['SIRENA', 'HOSPITAL', 'URGENCIA'],
    'BOMBEROS': ['CAMIÓN', 'ROJO', 'SIRENA'],
    'POLICÍA': ['COCHE', 'SIRENA', 'AZUL'],
    'TRACTOR': ['CAMPO', 'RUEDAS GRANDES', 'GRANJA'],
    'TRANVÍA': ['CIUDAD', 'VÍAS', 'ELÉCTRICO'],
    'METRO': ['SUBTERRÁNEO', 'TÚNEL', 'RÁPIDO'],
    'MONOPATÍN': ['TABLA', 'RUEDAS', 'TRUCOS'],
    'GLOBO': ['AIRE', 'VOLAR', 'CESTA'],
    'COHETE': ['ESPACIO', 'FUEGO', 'DESPEGAR'],
    'LIMUSINA': ['LUJO', 'LARGO', 'CHOFER'],
    'FURGONETA': ['ESPACIO', 'TRANSPORTE', 'VEHÍCULO'],
    'VELERO': ['VIENTO', 'MAR', 'VELAS'],
    'CANOA': ['REMOS', 'RÍO', 'BOTE'],
    'TRINEO': ['NIEVE', 'DESLIZAR', 'PERROS'],
    'CARRO': ['CABALLO', 'RUEDAS', 'ANTIGUO'],
    'GRÚA': ['LEVANTAR', 'OBRA', 'PESADO'],
    'EXCAVADORA': ['TIERRA', 'OBRA', 'PALA'],
    'PATINES': ['PIES', 'RUEDAS', 'DESLIZAR']
  },
  clothes: {
    'CAMISETA': ['MANGA', 'ALGODÓN', 'TORSO'],
    'PANTALÓN': ['PIERNAS', 'BOLSILLOS', 'CINTURÓN'],
    'FALDA': ['PIERNAS', 'MUJER', 'CORTO/LARGO'],
    'VESTIDO': ['ELEGANTE', 'MUJER', 'PIEZA'],
    'ZAPATOS': ['PIES', 'SUELA', 'CORDONES'],
    'ZAPATILLAS': ['DEPORTE', 'CÓMODO', 'CORDONES'],
    'CALCETINES': ['PIES', 'ALGODÓN', 'PAR'],
    'ABRIGO': ['INVIERNO', 'FRÍO', 'GRUESO'],
    'CHAQUETA': ['CREMALLERA', 'MANGA', 'ABRIGO'],
    'BUFANDA': ['CUELLO', 'LANA', 'INVIERNO'],
    'GUANTES': ['MANOS', 'DEDOS', 'FRÍO'],
    'GORRO': ['CABEZA', 'LANA', 'FRÍO'],
    'SOMBRERO': ['CABEZA', 'SOL', 'ELEGANTE'],
    'GAFAS': ['OJOS', 'SOL', 'VER'],
    'CINTURÓN': ['CINTURA', 'SUJETAR', 'HEBILLA'],
    'CORBATA': ['CUELLO', 'ELEGANTE', 'TRAJE'],
    'TRAJE': ['ELEGANTE', 'BODA', 'CHAQUETA'],
    'PIJAMA': ['DORMIR', 'CÓMODO', 'NOCHE'],
    'BAÑADOR': ['PLAYA', 'NADAR', 'VERANO'],
    'ROPA INTERIOR': ['DEBAJO', 'ÍNTIMO', 'DIARIO'],
    'CHÁNDAL': ['DEPORTE', 'CÓMODO', 'DOS PIEZAS'],
    'SUDADERA': ['CAPUCHA', 'ALGODÓN', 'DEPORTE'],
    'BOTAS': ['PIES', 'INVIERNO', 'LLUVIA'],
    'SANDALIAS': ['VERANO', 'PIES', 'ABIERTO'],
    'TACONES': ['ALTURA', 'MUJER', 'ELEGANTE'],
    'CHALECO': ['SIN MANGAS', 'ABRIGO', 'TORSO'],
    'IMPERMEABLE': ['LLUVIA', 'AGUA', 'PLÁSTICO'],
    'BATA': ['CASA', 'MÉDICO', 'ENCIMA'],
    'UNIFORME': ['TRABAJO', 'IGUAL', 'COLEGIO'],
    'DISFRAZ': ['FIESTA', 'MÁSCARA', 'PERSONAJE']
  },
  objects: {
    'MESA': ['MUEBLE', 'PATAS', 'COMER'],
    'SILLA': ['SENTARSE', 'RESPALDO', 'PATAS'],
    'CAMA': ['DORMIR', 'COLCHÓN', 'SÁBANAS'],
    'LÁMPARA': ['LUZ', 'BOMBILLA', 'ILUMINAR'],
    'RELOJ': ['TIEMPO', 'HORAS', 'MANECILLAS'],
    'ESPEJO': ['REFLEJO', 'VIDRIO', 'MIRARSE'],
    'LLAVE': ['ABRIR', 'CERRADURA', 'METAL'],
    'BOLÍGRAFO': ['ESCRIBIR', 'TINTA', 'PAPEL'],
    'CUADERNO': ['HOJAS', 'ESCRIBIR', 'PAPEL'],
    'MOCHILA': ['GUARDAR', 'LIBROS', 'ESPALDA'],
    'GAFAS': ['VER', 'LENTES', 'OJOS'],
    'TELÉFONO': ['LLAMAR', 'MÓVIL', 'PANTALLA'],
    'TAZA': ['BEBER', 'CAFÉ', 'ASA'],
    'PLATO': ['COMIDA', 'REDONDO', 'CERÁMICA'],
    'TENEDOR': ['COMER', 'PINCHAR', 'METAL'],
    'CUCHILLO': ['CORTAR', 'FILO', 'METAL'],
    'CUCHARA': ['SOPA', 'METAL', 'LÍQUIDO'],
    'BOTELLA': ['AGUA', 'PLÁSTICO/VIDRIO', 'BEBER'],
    'CAJA': ['CARTÓN', 'GUARDAR', 'CUADRADO'],
    'TIJERAS': ['CORTAR', 'FILO', 'MANUALIDAD'],
    'PARAGUAS': ['LLUVIA', 'MOJARSE', 'ABRIR'],
    'CARTERA': ['DINERO', 'TARJETAS', 'BOLSILLO'],
    'MONEDA': ['DINERO', 'METAL', 'REDONDO'],
    'BILLETE': ['DINERO', 'PAPEL', 'PAGAR'],
    'ORDENADOR': ['TECLADO', 'PANTALLA', 'TRABAJO'],
    'RATÓN': ['ORDENADOR', 'CLICK', 'MANO'],
    'TECLADO': ['TECLAS', 'ESCRIBIR', 'ORDENADOR'],
    'PANTALLA': ['VER', 'IMAGEN', 'LUZ'],
    'CABLE': ['CONECTAR', 'ELECTRICIDAD', 'LARGO'],
    'ENCHUFE': ['PARED', 'ELECTRICIDAD', 'CONECTAR']
  },
  body: {
    'CABEZA': ['PELO', 'CARA', 'PENSAR'],
    'BRAZO': ['MANO', 'FUERZA', 'EXTREMIDAD'],
    'PIERNA': ['ANDAR', 'PIE', 'RODILLA'],
    'MANO': ['DEDOS', 'COGER', 'TACTO'],
    'PIE': ['ZAPATO', 'ANDAR', 'DEDOS'],
    'OJO': ['VER', 'MIRAR', 'CARA'],
    'NARIZ': ['OLER', 'RESPIRAR', 'CARA'],
    'BOCA': ['COMER', 'HABLAR', 'DIENTES'],
    'OREJA': ['OÍR', 'ESCUCHAR', 'CARA'],
    'DIENTE': ['BOCA', 'MORDER', 'BLANCO'],
    'LENGUA': ['SABOR', 'BOCA', 'HABLAR'],
    'PELO': ['CABEZA', 'PEINAR', 'LARGO/CORTO'],
    'DEDO': ['MANO', 'UÑA', 'SEÑALAR'],
    'UÑA': ['DEDO', 'CORTAR', 'DURA'],
    'ESTÓMAGO': ['ARRIGA', 'COMIDA', 'DIGESTIÓN'],
    'CORAZÓN': ['LATIR', 'SANGRE', 'PECHO'],
    'PULMÓN': ['RESPIRAR', 'AIRE', 'PECHO'],
    'HUESO': ['ESQUELETO', 'DURO', 'BLANCO'],
    'SANGRE': ['ROJO', 'LÍQUIDO', 'VENAS'],
    'CEREBRO': ['PENSAR', 'CABEZA', 'MENTE'],
    'CUELLO': ['GARGANTA', 'CABEZA', 'BUFANDA'],
    'HOMBRO': ['BRAZO', 'ESPALDA', 'ARTICULACIÓN'],
    'CODO': ['BRAZO', 'DOBLAR', 'ARTICULACIÓN'],
    'RODILLA': ['PIERNA', 'DOBLAR', 'ARTICULACIÓN'],
    'ESPALDA': ['VERTEBRAS', 'ATRÁS', 'CARGAR'],
    'PECHO': ['TORSO', 'DELANTE', 'RESPIRAR'],
    'CINTURA': ['CINTURÓN', 'MEDIO', 'CUERPO'],
    'OMBLIGO': ['BARRIGA', 'CENTRO', 'AGUJERO'],
    'PIEL': ['TACTO', 'CUBRIR', 'SUAVE'],
    'MÚSCULO': ['FUERZA', 'MOVIMIENTO', 'CARNE']
  },
  school: {
    'COLEGIO': ['ESTUDIAR', 'PROFESOR', 'CLASE'],
    'PIZARRA': ['TIZA', 'BORRADOR', 'ESCRIBIR'],
    'LÁPIZ': ['ESCRIBIR', 'GOMA', 'MADERA'],
    'PROFESOR': ['ENSEÑAR', 'ALUMNOS', 'CLASE'],
    'LIBRO': ['LEER', 'PÁGINAS', 'ESTUDIAR'],
    'PATIO': ['JUGAR', 'RECREO', 'AIRE LIBRE'],
    'EXAMEN': ['NOTA', 'ESTUDIAR', 'PRUEBA'],
    'MOCHILA': ['LIBROS', 'ESPALDA', 'MATERIAL'],
    'RECREO': ['JUGAR', 'PATIO', 'DESCANSO'],
    'ASIGNATURA': ['MATERIA', 'CLASE', 'ESTUDIO'],
    'BOLÍGRAFO': ['TINTA', 'ESCRIBIR', 'AZUL'],
    'GOMA': ['BORRAR', 'LÁPIZ', 'PEQUEÑA'],
    'ESTUCHE': ['GUARDAR', 'LÁPICES', 'CREMALLERA'],
    'PUPITRE': ['MESA', 'SENTA', 'CLASE'],
    'DEBERES': ['CASA', 'TRABAJO', 'TARDE'],
    'NOTA': ['EXAMEN', 'NÚMERO', 'APROBAR'],
    'DIRECTOR': ['JEFE', 'DESPACHO', 'MANDAR'],
    'COMEDOR': ['COMER', 'BANDEJA', 'MEDIODÍA'],
    'GIMNASIO': ['DEPORTE', 'EDUCACIÓN FÍSICA', 'SUDAR'],
    'BIBLIOTECA': ['SILENCIO', 'LIBROS', 'LEER']
  },
  family: {
    'MADRE': ['MUJER', 'PARIR', 'AMOR'],
    'PADRE': ['HOMBRE', 'PAPÁ', 'AMOR'],
    'HERMANO': ['SANGRE', 'IGUAL', 'FAMILIA'],
    'ABUELO': ['VIEJO', 'MAYOR', 'NIETO'],
    'PRIMO': ['TÍO', 'FAMILIA', 'JUGAR'],
    'TÍO': ['PADRE', 'HERMANO', 'SOBRINO'],
    'BEBÉ': ['PEQUEÑO', 'LLORAR', 'PAÑAL'],
    'FAMILIA': ['UNIÓN', 'CASA', 'AMOR'],
    'HIJO': ['PADRES', 'PEQUEÑO', 'DESCENDENCIA'],
    'NIETO': ['ABUELO', 'PEQUEÑO', 'FAMILIA'],
    'SOBRINO': ['TÍO', 'HERMANO', 'NIÑO'],
    'CUÑADO': ['HERMANO', 'PAREJA', 'POLÍTICO'],
    'SUEGRO': ['PAREJA', 'PADRE', 'POLÍTICO'],
    'NUERA': ['HIJO', 'PAREJA', 'MUJER'],
    'YERNO': ['HIJA', 'PAREJA', 'HOMBRE'],
    'MARIDO': ['MUJER', 'CASADO', 'ESPOSO'],
    'MUJER': ['MARIDO', 'CASADA', 'ESPOSA'],
    'GEMELO': ['IDÉNTICO', 'HERMANO', 'DOS'],
    'MADRINA': ['BAUTIZO', 'REGALOS', 'MUJER'],
    'PADRINO': ['BAUTIZO', 'REGALOS', 'HOMBRE']
  },
  actions: {
    'CORRER': ['RÁPIDO', 'PIERNAS', 'DEPORTE'],
    'SALTAR': ['ARRIBA', 'PIERNAS', 'IMPULSO'],
    'COMER': ['BOCA', 'ALIMENTO', 'HAMBRE'],
    'DORMIR': ['CAMA', 'SUEÑO', 'NOCHE'],
    'LEER': ['LIBRO', 'OJOS', 'PALABRAS'],
    'ESCRIBIR': ['LÁPIZ', 'PAPEL', 'LETRAS'],
    'CANTAR': ['MÚSICA', 'VOZ', 'CANCIÓN'],
    'BAILAR': ['MÚSICA', 'MOVER', 'RITMO'],
    'REÍR': ['FELIZ', 'JAJAJA', 'ALEGRÍA'],
    'LLORAR': ['TRISTE', 'LÁGRIMAS', 'PENAS'],
    'NADAR': ['AGUA', 'PISCINA', 'MOJARSE'],
    'VOLAR': ['AIRE', 'ALAS', 'AVIÓN'],
    'COCINAR': ['COMIDA', 'FUEGO', 'PREPARAR'],
    'PENSAR': ['CEREBRO', 'IDEA', 'MENTE'],
    'HABLAR': ['BOCA', 'PALABRAS', 'VOZ'],
    'ESCUCHAR': ['OÍR', 'OREJAS', 'SONIDO'],
    'MIRAR': ['VER', 'OJOS', 'OBSERVAR'],
    'TOCAR': ['MANOS', 'SENTIR', 'PALPAR'],
    'OLER': ['NARIZ', 'AROMA', 'RESPIRAR'],
    'ANDAR': ['PIERNAS', 'CAMINAR', 'PASOS']
  },
  science: {
    'ÁTOMO': ['NÚCLEO', 'QUÍMICA', 'CIENCIA'],
    'PLANETA': ['ESPACIO', 'MUNDO', 'REDONDO'],
    'CÉLULA': ['VIDA', 'BIOLOGÍA', 'PEQUEÑO'],
    'ADN': ['GENÉTICA', 'CÓDIGO', 'HERENCIA'],
    'ESTRELLA': ['LUZ', 'CIELO', 'NOCHE'],
    'GRAVEDAD': ['CAER', 'PESO', 'TIERRA'],
    'ENERGÍA': ['LUZ', 'CALOR', 'FUERZA'],
    'TELESCOPIO': ['VER', 'ESTRELLAS', 'LENTES'],
    'MICROSCOPIO': ['VER', 'PEQUEÑO', 'LENTES'],
    'QUÍMICA': ['CIENCIA', 'FÓRMULAS', 'LABORATORIO'],
    'LABORATORIO': ['CIENCIA', 'EXPERIMENTO', 'BATA'],
    'CIENTÍFICO': ['PERSONA', 'SABIO', 'BATA'],
    'EXPERIMENTO': ['CIENCIA', 'PRUEBA', 'LABORATORIO'],
    'FÓRMULA': ['QUÍMICA', 'MATEMÁTICAS', 'PAPEL'],
    'IMÁN': ['METAL', 'AERRAER', 'POLO']
  },
  art: {
    'PINTURA': ['COLOR', 'CUADRO', 'ARTE'],
    'ESCULTURA': ['PIEDRA', 'ESTATUA', 'ARTE'],
    'MÚSICA': ['SONIDO', 'ARTE', 'NOTAS'],
    'DIBUJO': ['LÁPIZ', 'PAPEL', 'ARTE'],
    'PINCEL': ['PINTAR', 'COLORES', 'PELO'],
    'LIENZO': ['PINTAR', 'TELA', 'CUADRO'],
    'MUSEO': ['CUADROS', 'EXPOSICIÓN', 'ARTE'],
    'ARTISTA': ['GENIO', 'PINTOR', 'PERSONA'],
    'CABALLETE': ['MADERA', 'PINTAR', 'LIENZO'],
    'PÁLIDA': ['COLORES', 'PINTURA', 'MEZCLA'],
    'ACUARELA': ['AGUA', 'PINTURA', 'COLORES'],
    'RETRATO': ['CARA', 'PINTURA', 'FOTO'],
    'PAISAJE': ['NATURALEZA', 'PINTURA', 'VISTA'],
    'FOTOGRAFÍA': ['CÁMARA', 'IMAGEN', 'FOTO'],
    'CINE': ['PELÍCULA', 'ARTE', 'PANTALLA']
  },
  space: {
    'COHETE': ['VOLAR', 'ESPACIO', 'FUEGO'],
    'ASTRONAUTA': ['PERSONA', 'TRAJE', 'LUNA'],
    'SATELLITE': ['ESPACIO', 'ORBITA', 'TV'],
    'LUNA': ['CIELO', 'NOCHE', 'BLANCA'],
    'SOL': ['ESTRELLA', 'CALOR', 'DÍA'],
    'GALAXIA': ['ESTRELLAS', 'ESPACIO', 'GRANDE'],
    'METEORITO': ['PIEDRA', 'CIELO', 'CAER'],
    'COMETA': ['COLA', 'ESPACIO', 'HIELO'],
    'MARTE': ['PLANETA', 'ROJO', 'ESPACIO'],
    'JUPITER': ['PLANETA', 'GRANDE', 'GIGANTE'],
    'SATURNO': ['PLANETA', 'ANILLOS', 'ESPACIO'],
    'UNIVERSO': ['TODO', 'ESPACIO', 'INFINITO'],
    'ORBITA': ['VUELTA', 'CAMINO', 'REDONDO'],
    'GRAVEDADero': ['FLOTAR', 'ESPACIO', 'SIN PESO'],
    'VIAJE': ['IR', 'DISTANCIA', 'COHETE']
  },
  games: {
    'MARIO': ['NINTENDO', 'SALTAR', 'HONGOS'],
    'ZELDA': ['ESPADA', 'PRINCESA', 'AVENTURA'],
    'POKÉMON': ['CAPTURAR', 'BATALLA', 'EVOLUCIÓN'],
    'FORTNITE': ['BATTLE ROYALE', 'CONSTRUIR', 'BAILE'],
    'MINECRAFT': ['CUBOS', 'CONSTRUIR', 'CREATIVO'],
    'FIFA': ['FÚTBOL', 'BALÓN', 'GOL'],
    'CALL OF DUTY': ['GUERRA', 'DISPARAR', 'SOLDADO'],
    'GRAND THEFT AUTO': ['COCHE', 'CRIMEN', 'CIUDAD'],
    'ASSASSIN\'S CREED': ['SALTAR', 'ASASSINO', 'HISTORIA'],
    'THE SIMS': ['SIMULACIÓN', 'CASA', 'VIDA'],
    'ANGRY BIRDS': ['PÁJAROS', 'TIRAR', 'VERDE'],
    'CANDY CRUSH': ['DULCES', 'COMBINAR', 'PUZZLE'],
    'CLASH ROYALE': ['CARTAS', 'TORRES', 'BATALLA'],
    'AMONG US': ['IMPOSTOR', 'NAVE', 'TAREA'],
    'ROBLOX': ['CREAR', 'AVATAR', 'MUNDO'],
    'LEAGUE OF LEGENDS': ['MOBA', 'CAMPEONES', 'NEXUS'],
    'VALORANT': ['DISPAROS', 'AGENTES', 'RONDAS'],
    'COUNTER-STRIKE': ['TERRORISTAS', 'BOMBA', 'COMPETITIVO'],
    'OVERWATCH': ['HÉROES', 'OBJETIVO', 'EQUIPO'],
    'ROCKET LEAGUE': ['COCHE', 'BALÓN', 'GOL'],
    'FALL GUYS': ['OBSTÁCULOS', 'CAÍDA', 'DIVERSIÓN'],
    'APEX LEGENDS': ['BATTLE ROYALE', 'LEGENDS', 'ESCUADRA'],
    'WORLD OF WARCRAFT': ['MMORPG', 'MUNDO', 'MISIÓN'],
    'ELDER SCROLLS': ['FANTASÍA', 'DRAGÓN', 'AVENTURA'],
    'FINAL FANTASY': ['RPG', 'MAGIA', 'CRISTAL'],
    'STREET FIGHTER': ['PELEA', 'COMBOS', 'KEN'],
    'TEKKEN': ['PELEA', '3D', 'KASUYA'],
    'SUPER SMASH BROS': ['LUCHA', 'NINTENDO', 'PLATAFORMA'],
    'SPLATOON': ['TINTA', 'PINTAR', 'CALAMAR'],
    'ANIMAL CROSSING': ['ISLA', 'ANIMALES', 'RELAJANTE'],
    'STARDEW VALLEY': ['GRANJA', 'CULTIVAR', 'RELACIONES'],
    'HOLLOW KNIGHT': ['INSECTO', 'METROIDVANIA', 'ESPADA'],
    'CELESTE': ['PLATAFORMA', 'SALTAR', 'DIFICIL'],
    'UNDERTALE': ['RPG', 'DECISIONES', 'ALMA'],
    'CUPHEAD': ['DIBUJOS', 'JEFE', 'DIFÍCIL'],
    'HADES': ['ROGUELIKE', 'INFIERNO', 'DIOSES'],
    'DEAD CELLS': ['ROGUELIKE', 'METROIDVANIA', 'MUERTE'],
    'GEOMETRY DASH': ['RITMO', 'SALTAR', 'DIFÍCIL'],
    'SUBWAY SURFERS': ['CORRER', 'TREN', 'MONEDAS'],
    'TEMPLE RUN': ['CORRER', 'TEMPLO', 'OBSTÁCULOS']
  }
};


// Helper para obtener lista de palabras de una categoría
export function getWordsForCategory(category: string): string[] {
  const data = WORD_DATA[category] || WORD_DATA.general;
  return Object.keys(data);
}

// Helper para obtener una palabra similar para el impostor
export function getSimilarWord(category: string, secretWord: string): string {
  const data = WORD_DATA[category] || WORD_DATA.general;
  const similars = data[secretWord];
  if (similars && similars.length > 0) {
    return similars[Math.floor(Math.random() * similars.length)];
  }
  // Fallback: devolver categoría genérica
  const fallbacks: Record<string, string> = {
    general: 'OBJETO',
    animals: 'ANIMAL',
    food: 'COMIDA',
    movies: 'PELÍCULA',
    sports: 'DEPORTE',
    places: 'LUGAR',
    professions: 'PROFESIÓN',
    technology: 'TECNOLOGÍA',
    music: 'MÚSICA',
    history: 'HISTORIA',
    nature: 'NATURALEZA',
    fantasy: 'CRIATURA',
    vehicles: 'VEHÍCULO',
    clothes: 'ROPA',
    objects: 'OBJETO',
    body: 'PARTE DEL CUERPO',
    school: 'COLEGIO',
    family: 'FAMILIA',
    actions: 'ACCIÓN',
    colors: 'COLOR'
  };
  return fallbacks[category] || 'COSA';
}

// Mantener WORD_LISTS para compatibilidad
export const WORD_LISTS: Record<string, string[]> = Object.fromEntries(
  Object.entries(WORD_DATA).map(([cat, words]) => [cat, Object.keys(words)])
);

